[[main]]
identifier = "posts"
name = "Posts"
pageRef = "/posts"
weight = 10

[[main]]
identifier = "pages"
name = "Pages"
pageRef = "/pages"
weight = 15

[[main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 20
