# sass_transpiler: 'dartsass'
# Uncomment to use Dart Sass, you need to install Dart Sass first.

mainSections:
  - posts
  - pages

# titleSeparator: '|'
# Title separator. Default to -.

description: eyeofparadox.com on eyeofparadox.github.io
keywords: wordpress, content, posts, pages, fiction, essays, articles, art
# images:
  #  - site-feature-image.jpg

# metaRobots: noindex, nofollow
# Default value for Meta Tag robots
# metaRobots:
# disable Meta Tag robots

# logo: images/logo.png
# Logo image. Default to images/logo.webp.
# logo: false
# Disable Logo
brand: eyeofparadox

palette: blue
# Default palette. Optional. You'll need to clear the browser cache after modifying this.
# Available palettes. Default to ALL. Empty array means disable.
# palettes:
#  - blue
#  - blue-gray
#  - brown
#  - cyan
#  - green
#  - indigo
#  - orange
#  - pink
#  - purple
#  - red
#  - teal
#  - yellow

color: dark
# light, dark or auto. Default to auto.

# fullWidth: true
# Full width.
fixedHeader: true
# Set fixed header. # true false

dateFormat: ":date_long"

# Google Adsense
# googleAdsense:

# math: true
# Enable math globally. <<< implement KaTeX support first.
# toc: false
# Disable TOC globally.
# tocPosition: sidebar
# breadcrumb: false
# Disable breadcrumb
# breadcrumbDivider: >
# Breadcrumb divider
# diagram: true
# Enable diagram globally.
socialShare: false
# disable social network sharing
searchBar: false
# disable search-bar

poweredBy: false
# Whether to show powered by.

# readingTime: false
# Whether to display the reading time.
# postDate: false
# Whether to display the post date in the post meta section.

featuredPostCount: 10
# The number of featured posts shown in sidebar. Turn off by setting it to false.
recentPostCount: 10
# The number of recent posts shown in sidebar. Turn off by setting it to false.
relatedPostCount: 10
# The number of related posts. Turn off by setting it to false.
categoryCount: 50
# The number of categories shown in sidebar. Turn off by setting it to false.
tagCount: 100
# The number of tags shown in sidebar. Turn off by setting it to false.
seriesCount: 20
# The number of series shown in sidebar. Turn off by setting it to false.
# archivesCount: false
# archivesCount: 20
# The number of archives shown in sidebar. Turn off by setting it to false. 
taxonomyPaginate: 15
# Default to 10.
taxonomyPostCount: 50
# The number of taxonomy's posts. Turn off by setting it to false.
countTaxonomyPosts: true
# Count posts of taxonomy.

sidebarTaxonomies: [series, categories, tags]
# The order of taxonomies on the sidebar.

pinnedPost: true
# Turn on/off pinned posts.
pinnedPostCount: 7
# The number of pinned posts.

# Custom CSS and JS
customCSS:
customJS:

tocWordCount: 100
# TOC is displayed only if the post's word count exceeds this value.

titleCase: false
# Capitalized title. true

viewer: true
# Image Viewer

# backgroundImage: ['/images/bg-light.png', '/images/bg-dark.png']
rss: home
# link the RSS button to homepage all the times.

socialColor: false # Remove color from social links if false.

sidebar:
  # fixed: true
  # archives: false
  # archives: true
  # Enable archives widget
  # taxonomiesToggle: false
  # Disable taxonomy toggle
  # categories: true
  # Enable categories widget
  # tags: true
  # Enable tags widget
  # series: true
  # Enable series widget
  # authors: true
  # Enable authors widget
  # postsToggle: false
  # Disable posts toggle
  featuredPosts: true
  # Enable featured posts widget
  recentPosts: true
  # Enable featured posts widget
  # collapsed: true
  # Collapse sidebar widgets by default on small screens.

codeBlock:
  maxLines: 25
  lineNos: true
  # true/false represents that show/hide the line numbers by default.

post:
  # excerpt: description
  # excerptMaxLength: 120
  copyright: true
  # Whether to display copyright section on each post.
  # plainifyExcerpt: false
  # Format excerpt in HTML if false.
  featuredImage: true
  # Show the featured image above the content.
  numberifyHeadings: false
  # Count headings automatically.
  # numberifyHeadingsEndLevel: 4
  # The depth of headings to count. Default to 6.
  # numberifyHeadingsSeparator: .
  # The separator between of number and headings.
  # tocStyleType: decimal
  # The TOC's CSS list-style-type property.
  # imageTitleAsCaption: true
  # panel: false
  # Disable the post panel.
  # nav: false
  # Disable post navigations.
  # The page position after clicking the read more button, read more from content if true. Default to the beginning of page.
  # It supports only of the manual summaries spliting via <!---more--->.
  # readMoreFromContent: true

archive:
  paginate: 100
  # Archive pagination. Default to 100.
  basePath: "/posts"
  # basePath: "/archives"
  # The base path of archive pages.
  dateFormat: 2006-01-02
  # dateFormat: 01-02
  # Archive date format. Default to Jan 2.

# analytics:
# baidu:
# Baidu Analytics

# Site verification
siteVerification:
  google:
  bing:
  # baidu:
  # baiduUnion:
  # Baidu Union
  # so:
  # sogou:
  # shenma:

creativeCommons:
by: true
# Credit must be given to you, the creator.
nc: true
# Only noncommercial use of your work is permitted.
nd: true
# No derivatives or adaptations of your work are permitted.
sa: true
# Adaptations must be shared under the same terms.

# utterances:
# repo: eyeofparadox/eyeofparadox.github.io
# Replace with your repository.
  # issueTerm: pathname
  # pathname, url, title, og:title
  # label: comment
  # By default, light and dark mode correspond to github-light and github-dark, respectively.
  # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
  # theme: 

# staticman:
  # endpoint: https://yourstaticmaninstance
  # Required, replace with your own Staticman instance.
  # repo: user/repo
  # Required
  # service: github
  # or gitlab. Default to GitHub.
  # branch: main
  # Default to master.
  # property: comments
  # Default to comments.
  # sorting: desc
  # Default to asc.
  # reCaptchaKey: ""
  # The reCaptcha site key.
  # reCaptchaSecret: ""
  # The reCaptcha encrypted secret. You'll need to encrypt plain secret via https://yourstaticmaninstance/v3/encrypt/PLAINSECRET.
  # extraFields:
  # Extra fields. Available fiedls: url.
  #  - url
  # requiredFields:
  # Extra required fields. Available fields: email and the extra fields.
  #  - email
  #  - url
  # paginate: 5
  # Default to 10.
  # moderation: false
  # Same as Staticman's moderation.

# See https://giscus.app
# giscus:
  # repo: "eyeofparadox/eyeofparadox.github.io"
  # required.
  # repoId: "_"
  # required.
  # category: "General"
  # required.
  # categoryId: "_"
  # required.
  # theme: "dark"
  # Default to auto.
  # mapping: "title"
  # Default to pathname.
  # inputPosition: "bottom"
  # Default to top.
  # reactions: false
  # Disable reactions.
  # metadata: true
  # Emit discussion metadata.
  # lang: "en"
  # Specify language, default to site language.
  # lazyLoading: false
  # Default to true.

# search:
  # paginate: 5
  # Pagination. Default to 10.
  # resultContentWordCount: 240
  # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  # fuse:
    # ignoreLocation: true
    # location: 0
    # isCaseSensitive: false
    # minMatchCharLength: 1
    # threshold: 0.1
    # distance: 100
    # useExtendedSearch: true

#docsearch:
  # https://docsearch.algolia.com/docs/api
  # container: ".search-bar"
  # replace it if necessary, default to '.search-bar'.
  # appId: ""
  # apiKey: ""
  # indexName: ""
  # debug: true

# reward:
  # alipay: images/reward/alipay.png
  # wechat: images/reward/wechat.png
  # paypal: images/reward/paypal.png
  # patreon: images/reward/patreon.png
  # liberapay: images/reward/liberapay.png

#share:
  # addThis:
  # AddThis pubid.
  # actionsPanel:
   # disabled: true

# Comment or remove this settings to disable font size switcher.
# fontSize:
  # extraSmall: .8rem
  # small: .9rem
  # large: 1.1rem
  # extraLarge: 1.2rem

# pwa:
  # manifest:
    # name:
    # Default to site title.
    # short_name: eyeofparadox
    # display: fullscreen
    # Default to standalone.
    # description:
    # Default to site description.
    # theme_color:
   
    # background_color:
    # Icons
    # [[pwa.manifest.icons]]
      # sizes: 96x96
      # src: /images/icons/icon-96x96.png
    # [[pwa.manifest.icons]]
      # sizes: 144x144
      # src: /images/icons/icon-144x144.png

# contact:
  # endpoint: https://getform.io/f/56041c81-9e03-4c24-b9c5-61238854d4cd # <<< update with own keys
  # Backend endpoint, remove this line if you're using Netlify.
  # file: true
  # Enable file upload
  # fileField: image
  # The name of file field.
  # reCaptcha: # <<< update with own keys
    # siteKey: "6LcVyiAsAAAAAMIHZbVUQy4lJglVy-1fon16fcnD"

repo:
  url: https://github.com/eyeofparadox/
  branch: main
  subPath: eyeofparadox.github.io
  dateFormat: 02/01/2006, 15:04:05 PM

topAppBar:
  # See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
  social:
    github: eyeofparadox
    wordpress: eyeofparadox
    artstation: davidbryanroberson
    fab: davidbryanroberson
    patreon: davidbryanroberson
    paypal: eyeofparadox

docs:
  nav:
    # expand: true
    # Expand docs navigation.
    reduceFontSize: true
    # Reduce font size of children navigation.

#feeds:
  # content: true

social:
  email: eyeofparadox@outlook.com
  github: eyeofparadox
  wordpress: eyeofparadox
  artstation: davidbryanroberson
  fab: davidbryanroberson
  sketchfab: davidbryanroberson
  patreon: davidbryanroberson
  paypal: eyeofparadox
  deviantart: aeirn
  pinterest: davidbroberson
  instagram: davidbryanroberso
  tumblr: davidbroberson
  twitter: eyeofparadox
  # See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
  # facebook: yourfacebookusername
  # gitlab: yourgitlabusername
  # linkedin: yourlinkedinusername
  # xing: yourxingusername
  # stackoverflow: yourstackoverflowuserid
  # quora: yourquorausername
  # reddit: yourredditusername
  # telegram: yourtelegramusername
  # qq: yourqqnumber
  # dockerhub: yourdockerhubusername
  # bitbucket: yourbitbucketworkspaceid
  # kaggle: yourkaggleusername
  # medium: yourmediumusername
  # Medium username or custom domain(e.g. https://custom.domain.tld).
  # lastfm: yourlastfmusername
  # bilibili: yourbilibiliuserid
  # youtube: youryoutubechannelid
  # discord: yourdiscordinvitecode
  # discourse: https://yourforum.tld
  # facebookgroup: yourfacebookgroupname
  # tiktok: yourtiktokusername
  # mastodon: yourmastodonusername
  # liberapay: yourliberapayaccount
  # tipeee: yourtipeeeaccount-fr

author:
  name: eyeofparadox
  url: "https://github.com/eyeofparadox"
  # avatar: images/profile.png
  # Avatar image. Default to "images/profile.webp".
  bio: 'author, artist, content creator, amateur philosopher of physics and metaphysics.'
  company: eyeofparadox
  # HTML markup are supported, such as: <a href="https://eyeofparadox.com" target="_blank" rel="noopener noreferrer">Company</a>.
  location: Earth
  # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
  # about: https://www.artstation.com/davidbryanroberson/profile
  # The external about page. The internal about page will be used if not set.
  params: {
    # layout: compact
  }
  # See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
  social:
    email: eyeofparadox@outlook.com
    github: eyeofparadox/eyeofparadox.github.io
    twitter: eyeofparadox
    patreon: davidbryanroberson
    paypal: eyeofparadox
    # rss: ""
    # Remove RSS

# ---
# params from old .toml

# subtitle: "in the ashes of ideas hides the spark of understanding"
# keywords: "blog, echo, wordpress, posts, pages, essays, articles, fiction"
# contentTypeName: "posts"

# header:
  # logo: "logo.png"
  # title: "eyeofparadox"
  # fixedHeader: false
# Turn on/off fixed header.

# footer:
  # since: 2007
  # poweredby: true

