author:
  name: eyeofparadox
  url: "https://github.com/eyeofparadox"

  bio: 'author, artist, content creator, amateur philosopher of physics and metaphysics.'
  company: eyeofparadox 
  location: Earth 

social:
  email: eyeofparadox@outlook.com
  github: eyeofparadox
  wordpress: eyeofparadox
  artstation: davidbryanroberson
  fab: davidbryanroberson
  sketchfab: davidbryanroberson
  deviantart: aeirn
  pinterest: davidbroberson
  instagram: davidbryanroberso
  tumblr: davidbroberson
  twitter: eyeofparadox

dateFormat: ":date_long"

subtitle: "in the ashes of ideas hides the spark of understanding"
keywords: "blog, echo, wordpress, posts, pages, essays, articles, fiction"
contentTypeName: "posts"

header:
  logo: "logo.png"
  title: "eyeofparadox"
  fixedHeader: false 

footer:
  since: 2007
  poweredby: true

mainSections:
  - about
  - posts
  - pages
color: dark 

taxonomyPostCount: 50 
countTaxonomyPosts: true 

sidebarTaxonomies: [categories, tags, series] 
customCSS:
customJS:

tocWordCount: 1 

titleCase: true 

viewer: true 
sidebar:
  fixed: true

